## Numpy

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy
numpy.array

<function numpy.array>

In [8]:
import numpy as np

arr = [14,53,31,12,22]
arr

np_arr = np.array(arr)
np_arr

array([14, 53, 31, 12, 22])

In [14]:
## From list to 2D-array

arr = [[33,23],[24,64],[23,11]]
arr

arr1 = np.array(arr)
arr1

array([[33, 23],
       [24, 64],
       [23, 11]])

In [17]:
print(arr1.shape)

(3, 2)


## Numpy Built-in Functions

In [ ]:
## arange

In [23]:
import numpy as np

np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [27]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [29]:
np.random.rand(3,4)

array([[0.34837397, 0.1580242 , 0.88241096, 0.09704327],
       [0.50862444, 0.70204726, 0.20703449, 0.63281876],
       [0.97359761, 0.54117647, 0.13251108, 0.80989857]])

## Pandas

In [37]:
# Creating a pandas series from a list

import pandas as pd
a= [34,54,2,43,12,32,22]
b= pd.Series(a)
print(b)

0    34
1    54
2     2
3    43
4    12
5    32
6    22
dtype: int64


In [39]:
b.values

array([34, 54,  2, 43, 12, 32, 22], dtype=int64)

In [40]:
# Creating a series from dictionary

import pandas as pd

d = {'a':10, 'b':20, 'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

## Using index in a series

In [41]:
import pandas as pd

ser1 = pd.Series([1,2,3,4], index = ['India','USA','China','Brazil'])
ser1

India     1
USA       2
China     3
Brazil    4
dtype: int64

In [44]:
ser1['USA']

2

In [45]:
ser2 = pd.Series([1,2,3,4], index = ['India','USA','Italy','Brazil'])
ser2

India     1
USA       2
Italy     3
Brazil    4
dtype: int64

In [46]:
print(ser1+ser2)

Brazil    8.0
China     NaN
India     2.0
Italy     NaN
USA       4.0
dtype: float64


## DataFrames

In [52]:
import pandas as pd

df = pd.DataFrame([[1,2,3],
                   [3,4,5],
                   [5,6,7],
                   [7,8,9]])
df

0  1  2
0  1  2  3
1  3  4  5
2  5  6  7
3  7  8  9

In [53]:
print("Shape:", df.shape)

Shape: (4, 3)


In [56]:
df2 = pd.DataFrame([[2,4,3,1],[53,2,5,3],[66,45,23,2]], index=['a','b','c'], columns=['w','x','y','z'])
df2

w   x   y  z
a   2   4   3  1
b  53   2   5  3
c  66  45  23  2

In [57]:
df2.shape

(3, 4)

In [58]:
df2.index

Index(['a', 'b', 'c'], dtype='object')